pipeline:
  # The build phase
  build:
    image: phusion/baseimage
    commands:
      # get general stuff
      - apt-get update
      - apt-get install -y wget
      # download Emojicode
      - wget https://github.com/emojicode/emojicode/releases/download/v0.5/Emojicode-0.5.0-Linux-x86_64.tar.gz
      - tar xf Emojicode-0.5.0-Linux-x86_64.tar.gz
      - mkdir -p /usr/local/EmojicodePackages
      - cp -r Emojicode-0.5.0-Linux-x86_64/packages/* /usr/local/EmojicodePackages
      # Compile source
      - Emojicode-0.5.0-Linux-x86_64/emojicodec src/main.emojic

  # Build and deploy docker image
  docker:
    image: plugins/docker
    repo: magnificentpako/cancer
    tags: latest
    secrets: [ docker_username, docker_password ]